### ISSUE TITLE
No print button and preview wont work

### ISSUE THREAD

**Issue by burner-** [MultiMote/niimblue#1]
I try with D110. Some reason there is no print button and preview button does not do nothing 
![image](https://github.com/user-attachments/assets/0121b0e9-9e88-4ee6-b40c-58d64530203f)

**Comment by MultiMote** [comment]
Oops, my bad. I've pushed some intermediate build to the web server.
Fixed.

P.S. Code is changing constantly. If you see some issues, you can revisit page later. Most likely it will be fixed 🙂
