### ISSUE TITLE
Question about B1 support protocol

### ISSUE THREAD

**Issue by tywtyw2002** [MultiMote/niimblue#11]
Do you know the B1 printer support the ZPL protocal？

If not is possible to create a feature to translate ZPL to niimbot protocol?

**Comment by MultiMote** [comment]
B1 (and other portable Niimbot printers, I guess) can only print bitmaps.

I think the only way to print a ZPL image is to convert it to a bitmap and command-line projects like [niimprint](https://github.com/AndBondStyle/niimprint) more fits to this. I didn't find any js libraries to convert ZPL to image.

**Comment by tywtyw2002** [comment]
I saw some online ZPL viewer use labelary public api to convert ZPL to image.


https://labelary.com/service.html#limits

**Comment by MultiMote** [comment]
Added to [Roadmap](https://github.com/MultiMote/niimblue/issues/3).

The import will be done by converting the ZPL to PNG and adding it to the canvas if it is acceptable.

**Comment by MultiMote** [comment]
Done, added basic import option, you can check it now.

![image](https://github.com/user-attachments/assets/31e55173-7cba-4efd-a601-653d4391a0c8)

Tested with [test.zpl](https://github.com/user-attachments/files/16848835/test.zpl.txt)

**Comment by tywtyw2002** [comment]
Thanks, work greats!

I was busy in recently fews days, sorry for late reply.
