### ISSUE TITLE
Delete button removes the element even if the text input is active

### ISSUE THREAD

**Issue by jaggedjimmyj** [MultiMote/niimblue#18]
Title speaks for itself. "Delete" button on the keyboard removes the active element, even if this element is text and the input form is active too. Such behavior is not obvious and highly frustrating, when you just try to correct the text.

**Comment by MultiMote** [comment]
Yeah, this is known issue. I haven't gotten around to fixing it yet.

https://github.com/MultiMote/niimblue/blob/6f218f033effbeef7692363b46828c6e10a66ff6/niimblue/src/lib/ImageEditor.svelte#L55

**Comment by MultiMote** [comment]
Fixed.
