### ISSUE TITLE
feature request: center, print immediately

### ISSUE THREAD

**Issue by burner-** [MultiMote/niimblue#2]
Pleas make center button or even auto center check box. at some point. Niimbot original software is slow to use with all bell &whistlers. I like to see web app is fast to use so that use can just click sticker area, write text and press print.

**Comment by MultiMote** [comment]
I need some clarification. What centering do you mean? Vertical or horizontal? Relative to what? Vertical or horizontal?
Or you just want to put object on the label center?

**Comment by burner-** [comment]
Thanks. Those buttons are what I mean.  I just wondering that 90% of all labels are just one text at label. 
What you think about idea that by default sticker contain one text box with auto center/auto resize enabled. Then if user want modify layout them can disable those features by clicking property icons at object editor. 
That will help that at most cases user need just click that text and edit it and hit print. If printer is not connected print will pop up that connect dialog. If printer is connected it just print it without asking anything. Minimum amout of clicks when you just want basic sticker.

**Comment by MultiMote** [comment]
Okay, I'll think about how to make it suitable for most of users.
For now, I've made new text to be centered.

**Comment by MultiMote** [comment]
Added centered text as new label template.

**Comment by MultiMote** [comment]
Added print without preview button.
