### ISSUE TITLE
Cannot edit text on android

### ISSUE THREAD

**Issue by 123thecong** [MultiMote/niimblue#32]
Hello
I access it with android phone, but I can't edit text

**Comment by MultiMote** [comment]
Can't confirm with latest Chrome.
What browser are you using?

https://github.com/user-attachments/assets/9acf51e7-e34d-4020-9e84-d6aac7d26390

**Comment by 123thecong** [comment]
https://github.com/user-attachments/assets/ecc62c0b-768c-4e27-8f36-fa5789ddfd55

I am using samsung note 10+

**Comment by MultiMote** [comment]
Unfortunately, can't reproduce. Anyway, most likely it is [fabric.js](http://fabricjs.com) issue and I don't think I can fix it.

I've added "edit" button as workaround. Is this suitable for you?

https://github.com/user-attachments/assets/d73636c1-293e-4c29-b047-4e299dd0addf
