### ISSUE TITLE
Printing Indefinitely - D110

### ISSUE THREAD

**Issue by macattack69traf** [MultiMote/niimblue#33]
Have a new D110 printer. Through the app, when I hit print, the printer starts to print the same label, indefinitely. I have the number of copies set to 1, but it won't stop printing. I have to hit cancel within the UI, at which point, the printing stops.

I am running the server off OSX, and in the latest version of Chrome. 

Great project BTW!

**Comment by MultiMote** [comment]
What version of D110 do you have (203 dpi or 300 dpi with reverse feed support)? Can you send screenshot of printer info (gear button near printer name)?

I have same behaviour on my B1 when choosing V3 print task instead of V4. Try choosing V4 print task in print preview dialog and print again. If it working for you, you can press lock near print task.

**Comment by macattack69traf** [comment]
> I have same behaviour on my B1 when choosing V3 print task instead of V4. Try choosing V4 print task in print preview dialog and print again. If it working for you, you can press lock near print task.

This worked perfectly, thank you!!! Within the screen shot of the printer info, it stated that the printer is V4. changing a V4 print task works great. Thanks for the quick response!

**Comment by macattack69traf** [comment]
Thanks again!

**Comment by MultiMote** [comment]
Glad to hear!
Anyway, I still need your printer information to make V4 task default for it 🙂

**Comment by macattack69traf** [comment]
![Screen Shot 2024-10-10 at 10 54 18 PM](https://github.com/user-attachments/assets/a41399e8-773e-484e-b5cf-ea0744b9d331)

**Comment by macattack69traf** [comment]
One other note: I think that under the model metadata, with the DPI being 203, and the printer being 300, this is causing degradation in print quality.

**Comment by MultiMote** [comment]
Nice, thank you!

> DPI being 203, and the printer being 300, this is causing degradation in print quality

DPI is not using during prints. The single use of it is here - to convert mm to pixels:

![image](https://github.com/user-attachments/assets/363954e6-9112-42bd-9da9-431b52309156)

Printer operates with pixels units. So you should use 11.81 as dpmm. Can you make a photo of bad quality print and screenshot of print preview?

P.S. On you screenshot protocolVersion=4. There is not same as print task version. protocolVersion is some sort of "printer revision" and used to change some aspects of packet sending in official applications. Currently it have no uses in niimblue.
