### ISSUE TITLE
Save/Load Label Settings to/from JSON

### ISSUE THREAD

**Issue by tuffnerdstuff** [MultiMote/niimblue#38]
Hi!

I'm not sure if this is planned as part of the roadmap already, but it would be super useful to be able to export/import the label settings (height, width, etc. the settings behind the cogwheel icon) to/from JSON the way it can be done for the label contents. Currently it seems the settings are stored in the local storage of the browser. It would be nice to offer saving one or more of the settings in one JSON file. That way one can easily restore/share all settings for all available label types.

Best regards
tuffnerdstuff

P.S.: awesome work, the web app runs flawlessly on my phone and my PC 👌

**Comment by tuffnerdstuff** [comment]
The issue was tagged as "bug" by mistake. I wanted to change it to "enhancement" but it seems that is not possible anymore. Feel free to change it!

**Comment by MultiMote** [comment]
Are you running up-to-date version?
If I understand you correctly, it is already implemented.

![image](https://github.com/user-attachments/assets/9bbd7cbf-d6d1-482f-a87b-14417a2cb0c3)

![image](https://github.com/user-attachments/assets/8280ce9d-7aa7-441e-ad3a-5191ffef52a0)

**Comment by MultiMote** [comment]
That's a good point. I will implement this soon. Added to [Roadmap](https://github.com/MultiMote/niimblue/issues/3).

**Comment by MultiMote** [comment]
Done.

![image](https://github.com/user-attachments/assets/35ff7c1b-0321-41c8-b3e3-6bc60fe543f2)

**Comment by tuffnerdstuff** [comment]
Wow, that was fast 👌 Great work!
