### ISSUE TITLE
Import images ( load from png )

### ISSUE THREAD

**Issue by DarkosGahan** [MultiMote/niimblue#4]
Hi,

This is more an encouraging message than a feature request since I saw importing images was already in the roadmap.
It is great to see such project since niimbot seem too lazy do develop tools for linux. 

I own a B1 but if you would need a tester, you can contact me.

**Comment by MultiMote** [comment]
Button added.

![image](https://github.com/user-attachments/assets/e95e3e70-f5f8-4fed-b10f-91e52cb039e3)
