### ISSUE TITLE
Configuration the Port for the Website

### ISSUE THREAD

**Issue by frober** [MultiMote/niimblue#40]
Hello, is it possible to change the Port for the Webserver? I would like to start it on my NAS and the Port 80 is already used.

**Comment by MultiMote** [comment]
How did you run your instance?

For Docker installation:

```
docker run --name niimblue -p <ANY_PORT_HERE>:80 -d ghcr.io/multimote/niimblue:latest
```

Keep in mind that you need to configure SSL if you will be accessing by address other than localhost.

More info here:

https://github.com/MultiMote/niimblue/wiki/Running-own-instance-with-Docker

**Comment by frober** [comment]
Thanks for the solution. At the time I don't use docker. I will look at this. To start it directly in the main system, is not possible with the Port as parameter?

**Comment by MultiMote** [comment]
What commands are you using to start the server?

**Comment by frober** [comment]
I don't have installed it yet. I tested your Demo and I like it. Many thanks for your Work.  
I thought "yarn dev-check" ist the start command. Ist this not right? 
Sorry that I use your time. I think that I use the docker solution.

**Comment by MultiMote** [comment]
> I thought "yarn dev-check" ist the start command. Ist this not right?

To start development server you should run `yarn install` to install dependencies and `yarn dev` to start the server.

By default it listens **127.0.0.1** with port **5173**. To change it (for example, to 0.0.0.0:5000) use `yarn dev --port 5000 --host 0.0.0.0`

Remember, this is **development** server. It used for **development**.

For production installation you should run `yarn build` and then copy static contents of `dist` folder to your web server's (apache, nginx, etc.) html root. This application does not contains server side, it consists only of static html/js/css/... files.

**Comment by frober** [comment]
Thank you for your explanation. That helps me and I learned something new. 
I hadn't seen the wiki, it doesn't show up in the mobile browser. Otherwise I might not have asked. Have a nice Weekend.

**Comment by MultiMote** [comment]
You're welcome.
If you have any more questions, I'd be glad to help.
