### ISSUE TITLE
Offset for labels

### ISSUE THREAD

**Issue by mapsrof** [MultiMote/niimblue#41]
I'm using a B1 printer and deployed NiimBlue as docker container. Working great, thanks a lot for your effort - loving it!

Nevertheless I need to shift all items two times to the left, to make it centered on the printed label. It would be very useful, if you could implement a way to set an offset at the label preferences.

Another thing I see missing in regard of label preferences is an option to use round stickers.

**Comment by MultiMote** [comment]
Thank you for your kind words!

To implement your suggestion, I need to understand how it would work.

> shift all items two times to the left

How should this differ from just moving the content with your mouse/keyboard (if you go beyond the dimensions of the canvas, you can increase its size if your printer's resolution allows it)?

> I see missing in regard of label preferences is an option to use round stickers

What this option should do? I think round labels will be printed as usual ones. Canvas background with circle?

**Comment by MultiMote** [comment]
Added print offset in print preview dialog.

![LocnEHXWIx](https://github.com/user-attachments/assets/8f882350-f137-46c7-b7ad-b04ac60ea388)

![NVIDIA_Share_JReAEaHQua](https://github.com/user-attachments/assets/a1fd7fcb-1077-4e51-9a4f-d416afc3aa46)

![NVIDIA_Share_fAgoAYyS1e](https://github.com/user-attachments/assets/6e0cfba5-15e6-4094-8f2e-411c8ce230d3)

**Comment by mapsrof** [comment]
Absolutely great! Tested with new github-deployment and working fine. Thanks a lot for your effort.

**Comment by MultiMote** [comment]
@mapsrof so what about round stickers? What this option should do?
