### ISSUE TITLE
Can't pair D11 with Tp-Link UB500

### ISSUE THREAD

**Issue by danielwerg** [MultiMote/niimblue#43]
* Transport:
- [x] Bluetooth (Tp-Link UB500)
- [ ] Serial (USB)

*describe your issue here*

- 6.11.5-artix1-1

Trying to pair using `bluetui` and I'm getting generic error: `Error Bluetooth authentication failed: Authentication Failed`

On android I _have_ to enable "location" service in order to pair the printer, maybe this is related?

**Comment by MultiMote** [comment]
I have same adapter and I found no issues when tried to repeat your setup. I am not familiar with Arch. What I did:

1. Stated Artix Xfce live image - https://ftp.crifo.org/artix/iso/artix-lxde-openrc-20240823-x86_64.iso

2. Added omniverse repo

![image](https://github.com/user-attachments/assets/50cd1163-5e6d-49a9-aa66-18a7d307ea61)

3. Installed chromium: `pacman -Sy`, `pacman -S ungoogled chromium`

4. Enabled Bluetooth
![image](https://github.com/user-attachments/assets/10a0a408-c95e-4594-862b-09dc2f66b970)

5. Started chromium, enabled experimental web features (`chrome://flags`)
![image](https://github.com/user-attachments/assets/77d75a03-dfee-4018-8537-117fce3f72b2)

6. Restarted chromium and connected my printer

![image](https://github.com/user-attachments/assets/ed9cfb72-280a-4d5e-9698-0146aa5f2a58)

![image](https://github.com/user-attachments/assets/ff8cd667-70d9-4d39-bc95-a8d45a574945)

There is no need to pair printer manually.

**Comment by danielwerg** [comment]
Thank you for such detailed instructions! I'm not very familial with bluetooth, I never even opened website in chromium because I couldn't manually pair the printer XD
Gonna be so much easier to debug now, hate the damn phones.

Maybe it's worth adding some parts of your comment to README for people like me.
