### ISSUE TITLE
Word wrapping for dynamic data

### ISSUE THREAD

**Issue by tomermurray** [MultiMote/niimblue#44]
Would it be possible to add some way of wrapping text so that it doesn't go out of the bounds of the text object

![image](https://github.com/user-attachments/assets/5dc2bb86-7f94-4152-8ca8-9328ccf428d5)

In this example the text is too long to fit on the label but it would fit if it went onto another line

![image](https://github.com/user-attachments/assets/451cbb71-b719-47a0-a11e-6bcb9e3cef7d)

**Comment by MultiMote** [comment]
Fixed. It's a wonder I didn't do it sooner 😄

![image](https://github.com/user-attachments/assets/0e4b0445-9447-4794-935b-9844ca64dd8a)

![image](https://github.com/user-attachments/assets/9541bcdc-bcd0-4a1f-b318-3f3107548e7d)

**Comment by tomermurray** [comment]
Wow, that was so quick.
Thank you so much
