### ISSUE TITLE
Can we use this in ionic apps with BLE plugin ?

### ISSUE THREAD

**Issue by dotnetdreamer** [MultiMote/niimblue#47]

**Comment by MultiMote** [comment]
Not sure for Ionic, but I think it is definitely possible with [Apache Cordova](https://cordova.apache.org/).
It is required to implement custom client that using [cordova-plugin-ble-central](https://github.com/don/cordova-plugin-ble-central) instead of `navigator.bluetooth` and use it [here](https://github.com/MultiMote/niimblue/blob/79276ab41d42539e285fd4d07ecc942e1275b1b3/src/stores.ts#L39).

Example of non-browser client implementation you can see [here](https://github.com/MultiMote/niimbluelib-headless/tree/main/src/client) (i've tried to use nodejs as backend).

**Comment by idrees-khan1** [comment]
Not having plugin for ionic/capacitor is a missed opportunity...

**Comment by dotnetdreamer** [comment]
Not having plugin for ionic/capacitor is a missed opportunity...

**Comment by MultiMote** [comment]
As far as I know, Ionic/Сapacitor is built on Cordova so ble plugin may be compatible.

**Comment by dotnetdreamer** [comment]
Hi, i tried to following the links you shared and created a test app which i will use and make it public for other peoples as well. However, i am facing an issue [here](https://github.com/dotnetdreamer/capacitor-niimbot-printer-test/blob/7ff4a85e8958660b417b3e3f075947257f4a0a47/src/app/NiimbotBluetoothCapacitorClient.ts#L65C20-L65C36)
Check this below. Not sure whats going on...

![image](https://github.com/user-attachments/assets/695cc58d-d0ee-4097-9372-0a84b71dd95e)

Video 

https://github.com/user-attachments/assets/72ab791a-ad1b-411d-9633-06f269027bcc

**Comment by dotnetdreamer** [comment]
If you want to run the repo, the npm i, ionic build and then ionic capacitor run android.

**Comment by MultiMote** [comment]
https://github.com/dotnetdreamer/capacitor-niimbot-printer-test/blob/7ff4a85e8958660b417b3e3f075947257f4a0a47/src/app/NiimbotBluetoothCapacitorClient.ts#L154

You pass strings "service_uuid" "characteristic_uuid" to the `write` function. It should be variables (discovered printer UUIDs).

I wrote some info here (related to service and characteristic UUID discovery):

https://multimote.github.io/niimbluelib/documents/NIIMBOT_hardware_interfacing.html#md:bluetooth-low-energy

**Comment by dotnetdreamer** [comment]
I already have discoveredobject in above screenshot. Is it should be from characteristics property?

**Comment by dotnetdreamer** [comment]
As you can see i can't figure out which charactarist and service needs to be passed...

```
{
  "name": "B1-G522072694",
  "id": "22:05:07:4F:1B:69",
  "advertising": {},
  "rssi": -53,
  "connectable": true,
  "services": [
    "1801",
    "1800",
    "49535343-fe7d-4ae5-8fa9-9fafd205e455",
    "e7810a71-73ae-499d-8c15-faa9aef0c3f2"
  ],
  "characteristics": [
    {
      "service": "1801",
      "characteristic": "2a05",
      "properties": [
        "Indicate"
      ],
      "descriptors": [
        {
          "uuid": "2902"
        }
      ]
    },
    {
      "service": "1800",
      "characteristic": "2a00",
      "properties": [
        "Read",
        "WriteWithoutResponse",
        "Write",
        "AuthenticateSignedWrites"
      ]
    },
    {
      "service": "1800",
      "characteristic": "2a01",
      "properties": [
        "Read",
        "WriteWithoutResponse",
        "Write",
        "AuthenticateSignedWrites"
      ]
    },
    {
      "service": "1800",
      "characteristic": "2a04",
      "properties": [
        "Read"
      ]
    },
    {
      "service": "49535343-fe7d-4ae5-8fa9-9fafd205e455",
      "characteristic": "49535343-1e4d-4bd9-ba61-23c647249616",
      "properties": [
        "Read",
        "Notify"
      ],
      "descriptors": [
        {
          "uuid": "2902"
        }
      ]
    },
    {
      "service": "49535343-fe7d-4ae5-8fa9-9fafd205e455",
      "characteristic": "49535343-8841-43f4-a8d4-ecbe34729bb3",
      "properties": [
        "Write"
      ]
    },
    {
      "service": "49535343-fe7d-4ae5-8fa9-9fafd205e455",
      "characteristic": "49535343-6daa-4d02-abf6-19569aca69fe",
      "properties": [
        "WriteWithoutResponse"
      ]
    },
    {
      "service": "49535343-fe7d-4ae5-8fa9-9fafd205e455",
      "characteristic": "49535343-aca3-481c-91ec-d85e28a60318",
      "properties": [
        "Read",
        "Write",
        "Notify"
      ],
      "descriptors": [
        {
          "uuid": "2902"
        }
      ]
    },
    {
      "service": "e7810a71-73ae-499d-8c15-faa9aef0c3f2",
      "characteristic": "bef8d6c9-9c21-4c9e-b632-bd58c1009f9f",
      "properties": [
        "Read",
        "WriteWithoutResponse",
        "Notify"
      ],
      "descriptors": [
        {
          "uuid": "2902"
        }
      ]
    }
  ]
}
```

![image](https://github.com/user-attachments/assets/4e818b56-43f8-495d-ba1a-a3de6dc58235)

**Comment by dotnetdreamer** [comment]
I tried, 
 const characteristic = this.device.characteristics[this.device.characteristics.length - 1];
        ble.write(this.device.id, characteristic.service, characteristic.characteristic, data.buffer, () => {
          this.emit("rawpacketsent", new RawPacketSentEvent(data));
        }, (err) => {
          throw err;
        });
        
This works but now getting further issues
![image](https://github.com/user-attachments/assets/5fab0937-cec2-4515-aa8b-0314254d25ee)

**Comment by MultiMote** [comment]
As I wrote in documentation, you should do this:

> You can interact with printer through a specific BLE characteristic. To find what characteristic is suitable for this:
>
> Find services which have UUID length > 4.
>
> Find characteristic in these services which have NOTIFY and WRITE_NO_RESPONSE properties.

Correct ones are these, but you should get it by iterating and filtering. You can hardcode it for testing:

![image](https://github.com/user-attachments/assets/4f78f50f-8e04-4c64-99e3-27700d9aee0d)

I hardcoded it to niimbluelib because Web Bluetooth does not allow to see all services: https://github.com/MultiMote/niimbluelib/blob/main/src/client/bluetooth_impl.ts#L8-L9

I will check out your project when I get home.

**Comment by MultiMote** [comment]
Can you push your changes?

**Comment by dotnetdreamer** [comment]
I have pushed all :)

**Comment by MultiMote** [comment]
> If you want to run the repo, the npm i, ionic build and then ionic capacitor run android.
I am not familiar with Ionic. What to do next? How to get debug output?

![NVIDIA_Share_MmabhPDM89](https://github.com/user-attachments/assets/b26fbcdb-306c-4e3d-9708-bffad1303b39)

I get example app deployed to android.

![image](https://github.com/user-attachments/assets/720c31f4-8ecd-4213-96d4-7d33416ff9f1)

**Comment by MultiMote** [comment]
Figured out.
Error is thrown because packed is fragmented. I'll fix it, wait a little bit.

![image](https://github.com/user-attachments/assets/bdd9c0c7-d750-46fe-99d1-43a1d3bcce64)

**Comment by MultiMote** [comment]
Done, try this:


<details>
<summary>NiimbotBluetoothCapacitorClient.ts</summary>

```ts
/// <reference types="cordova-plugin-ble-central" />

import {
  ConnectionInfo,
  NiimbotAbstractClient,
  ConnectResult,
  NiimbotPacket,
  ResponseCommandId,
  Utils,
  ConnectEvent,
  DisconnectEvent,
  PacketReceivedEvent,
  RawPacketReceivedEvent,
  RawPacketSentEvent,
} from '@mmote/niimbluelib';

// cordova-plugin-ble-central has no disconnect events
export class NiimbotBluetoothCapacitorClient extends NiimbotAbstractClient {
  // private mac: string;
  private device: any;
  private readonly _props = ['Read', 'WriteWithoutResponse', 'Notify'];
  private serviceUUID: string = '';
  private characteristicUUID: string = '';
  private packetBuf = new Uint8Array();

  constructor(mac: string) {
    super();
    // this.mac = mac;
  }

  private async tryConnect(): Promise<void> {
    // fixme: do not use async in Promise!
    return new Promise(async (resolve, reject) => {
      const devices = await ble.withPromises.bondedDevices();
      console.log('bondedDevices', devices);

      this.serviceUUID = '';
      this.characteristicUUID = '';

      ble.scan(
        [],
        5,
        async (data) => {
          if (!data.name?.startsWith('B1-')) {
            return;
          }

          await ble.withPromises.stopScan();

          ble.connect(
            data.id,
            async (device: any) => {
              console.log('onConnect', device);

              localStorage.setItem('device', JSON.stringify(device));
              this.device = device;

              const characteristic = this.device.characteristics.find(
                (c: { properties: string[] }) =>
                  this._props.every((prop) => c.properties.includes(prop))
              );

              if (characteristic === undefined) {
                throw new Error('Characteristic not found');
              }

              this.serviceUUID = characteristic.service;
              this.characteristicUUID = characteristic.characteristic;

              await ble.withPromises.startNotification(
                this.device.id,
                this.serviceUUID,
                this.characteristicUUID,
                this.rawPacketReceived.bind(this),
                reject
              );

              resolve(this.device);
            },
            reject
          );
        },
        (error) => {
          reject(new Error('No device found'));
        }
      );
    });
  }

  public async connect(): Promise<ConnectionInfo> {
    //check if device was previously connected, we need to disconnect it first
    try {
      this.device = JSON.parse(localStorage.getItem('device') as string);
    } catch (e) {}

    await this.disconnect();
    await this.tryConnect();

    try {
      try {
        await this.initialNegotiate();
      } catch (e) {
        console.error('initialNegotiate error', e);
      }

      const info = await this.fetchPrinterInfo();
      console.log('printer info', info);
    } catch (e) {
      console.error('Unable to fetch printer info.', e);
      console.error(e);
    }

    const result: ConnectionInfo = {
      deviceName: `Bluetooth (${this.device.id})`,
      result: this.info.connectResult ?? ConnectResult.FirmwareErrors,
    };

    this.emit('connect', new ConnectEvent(result));

    return result;
  }

  private rawPacketReceived(buffer: ArrayBuffer) {
    if (buffer.byteLength === 0) {
      return;
    }

    const data = new Uint8Array(buffer);

    const newBuf = new Uint8Array(this.packetBuf.length + data.length);
    newBuf.set(this.packetBuf, 0);
    newBuf.set(data, this.packetBuf.length);
    this.packetBuf = newBuf;

    try {
      const packets: NiimbotPacket[] = NiimbotPacket.fromBytesMultiPacket(
        this.packetBuf
      );

      if (packets.length > 0) {
        this.emit('rawpacketreceived', new RawPacketReceivedEvent(this.packetBuf));

        packets.forEach((p) => {
          this.emit('packetreceived', new PacketReceivedEvent(p));
        });

        this.packetBuf = new Uint8Array();
      }
    } catch (_e) {
      if (this.debug) {
        console.info(`Incomplete packet, ignoring:${Utils.bufToHex(this.packetBuf)}`);
      }
    }
  }

  public isConnected(): boolean {
    return this.device !== undefined;
  }

  public async disconnect() {
    this.stopHeartbeat();

    if (this.device) {
      ble.disconnect(
        this.device.id,
        () => {
          this.emit('disconnect', new DisconnectEvent());
        },
        (err) => {
          console.error('Error during disconnect', err);
        }
      );
      this.device = undefined;
    }
  }

  public async sendRaw(data: Uint8Array, force?: boolean) {
    const send = async () => {
      if (!this.isConnected()) {
        this.disconnect();
        throw new Error('Disconnected');
      }

      await Utils.sleep(this.packetIntervalMs);

      ble.write(
        this.device.id,
        this.serviceUUID,
        this.characteristicUUID,
        data.buffer,
        () => {
          this.emit('rawpacketsent', new RawPacketSentEvent(data));
        },
        (err) => {
          throw err;
        }
      );
    };

    if (force) {
      await send();
    } else {
      await this.mutex.runExclusive(send);
    }
  }
}
```
</details>

I've used same approach for serial: https://github.com/MultiMote/niimbluelib/blob/7988d46d0c6699e81ba3d9e692d90658724af65c/src/client/serial_impl.ts#L65-L108

**Comment by idrees-khan1** [comment]
I will wait for the new release then. I am using npm package

**Comment by dotnetdreamer** [comment]
![image](https://github.com/user-attachments/assets/ba72804a-93b4-4a4e-bfcb-2431c1b09076)
i have TS error

**Comment by MultiMote** [comment]
> Also you need to update niimbluelib to 0.0.1-alpha.18.

I've added default implementation for `sendPacketWaitResponse` so you don't need to implement own.

**Comment by dotnetdreamer** [comment]
i copied your code and getting this 
```
PrinterService.ts:161  TypeError: Cannot read properties of null (reading 'id')
    at NiimbotBluetoothCapacitorClient.ts:182:21
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:17:1)
    at _ZoneDelegate.invoke (zone.js:369:28)
    at Object.onInvoke (core.mjs:7251:33)
    at _ZoneDelegate.invoke (zone.js:368:34)
    at ZoneImpl.run (zone.js:111:43)
    at zone.js:2538:40
    at _ZoneDelegate.invokeTask (zone.js:402:33)
```
seems that `this` isn't binding correctly

**Comment by MultiMote** [comment]
NiimbotBluetoothCapacitorClient.device is null for some reason. Try to understand why.

* Why are you storing device to localStorage?
* According to `resolve(this.device)` `tryConnect()` should return `Promise<SomeDeviceType>` not `Promise<void>`

P.S. I will add [cordova-plugin-ble-central](https://github.com/don/cordova-plugin-ble-central) client implementation to the niimbluelib library a little later. I'm interested in a standalone android app too.

**Comment by dotnetdreamer** [comment]
I am storing on localstorage temporarily because i am applying changes and it keeps refreshing live. 
With regards to cordova-plugin-ble-central, i guess best to not use cordova plugins and instead use capacitor plugins. I just want make this work and then will try the best way later. 
The issue now i am facing is the image encoder. I am looking for encoder that works on web :)

**Comment by dotnetdreamer** [comment]
instead of adding [cordova-plugin-ble-central](https://github.com/don/cordova-plugin-ble-central), i would suggest to wrap the working code inside a capacitor plugin. Because cordova is dead and future is capacitor. However if you want to add deps on that then a global object check on ble-central plugin can also be an option.

**Comment by dotnetdreamer** [comment]
wow so cool. The library will open more doors :) i will check the links

**Comment by dotnetdreamer** [comment]
The apk worked with me but the readme instructions not clear to me. So i couldn't test it.
Here is the apk result.
[![Screenshot_20241116_155050_NiimBlues.jpg](https://github.com/user-attachments/assets/bbb02686-0e37-43ad-815e-bac2f1c87ff4)

![20241116_155124.jpg](https://github.com/user-attachments/assets/6ed8d7f6-7335-434d-a885-71d59eeb85dd)

![20241116_155124.jpg](https://github.com/user-attachments/assets/8655856d-d5ce-449c-ac6f-eda98dd422b6)

**Comment by dotnetdreamer** [comment]
my requirement was to download this label from the nimblue UI as json and then in my own app, i should be able to send it to printer. I will do my part and then test it.

**Comment by MultiMote** [comment]
[@mmote/niimbluelib@0.0.1-alpha.19](https://github.com/MultiMote/niimbluelib/commit/dad965933eb9cfb1049be2ce0908b1a8ed153ebf) released

**Comment by dotnetdreamer** [comment]
I will test it in a while

**Comment by dotnetdreamer** [comment]
I managed to redirect to this repo from my app. However it isnt able to find device
https://github.com/user-attachments/assets/8a8a4a6f-b052-4271-9bdb-b0785aa7e18d

**Comment by dotnetdreamer** [comment]
I was missing permission. Its fine now.
Now i see each time print, prints twice...
https://github.com/user-attachments/assets/2de49d24-1183-49c0-a05e-d8cc73dd5485

**Comment by MultiMote** [comment]
You enabled CSV data so two page printed

**Comment by dotnetdreamer** [comment]
yes worked :P

I see that printerDirection isn't applied again onload if already set in localstorage. If the values are saved and you refresh the browser, they aren't picked up automatically next time.

![image](https://github.com/user-attachments/assets/b12d34cb-2011-45ff-8bcf-0415e7650670)

**Comment by MultiMote** [comment]
It is intended.
You need to press this button to load exiting setting to the form (there was some reactivity problems so I had to do this).

![image](https://github.com/user-attachments/assets/ed9b0366-887d-4a02-ba40-a4bfe744e5cc)

P.S. Updated [capacitor](https://github.com/MultiMote/niimblue/tree/capacitor) branch so building will be easer if you need it.

**Comment by dotnetdreamer** [comment]
oh, in my case my app is setting these values by default in localstorage and then it is redirected to your web app which loads all this data pre-filled. I will try your solution. I can maybe onMount press that button to laod by default

**Comment by dotnetdreamer** [comment]
Add tick worked for me. Can you check at your side ?

```
  onMount(async () => {
    const defaultPreset: LabelPreset = DEFAULT_LABEL_PRESETS[0];
    width = defaultPreset.width;
    height = defaultPreset.height;
    prevUnit = defaultPreset.unit;
    unit = defaultPreset.unit;
    printDirection = defaultPreset.printDirection;

    try {
      const savedPresets: LabelPreset[] | null = LocalStoragePersistence.loadLabelPresets();
      if (savedPresets !== null) {
        labelPresets = savedPresets;
      }
    } catch (e) {
      Toasts.zodErrors(e, "Presets load error:");
    }

    **await tick(); // Wait for the next DOM update cycle
    fillWithCurrentParams();
  });**
```

**Comment by MultiMote** [comment]
The problem was in updating these parameters when you load label from save/load label (sdcard icon) menu.

**Comment by dotnetdreamer** [comment]
> The problem was in updating these parameters when you load label from save/load label (sdcard icon) menu.
> 
> UPD: [388d3cf](https://github.com/MultiMote/niimblue/commit/388d3cf2ace4e7ed3e41db24e15a0934edb9d306)

worked in web and mobile thanks (y)

**Comment by MultiMote** [comment]
You can subclass NiimbotCapacitorBleClient and rewrite the `connect` function.

You can remove `const device: BleDevice = await BleClient.requestDevice();` line and set `this.deviceId` to your printer's BLE MAC instead. Or you can use [Scanning API](https://github.com/capacitor-community/bluetooth-le?tab=readme-ov-file#scanning-api).

**Comment by dotnetdreamer** [comment]
> You make a copy of NiimbotCapacitorBleClient and rewrite the `connect` function.
> 
> You can remove `const device: BleDevice = await BleClient.requestDevice();` line and set `this.deviceId` to your printer's BLE MAC instead. Or you can use [Scanning API](https://github.com/capacitor-community/bluetooth-le?tab=readme-ov-file#scanning-api).

How about providing an overload in constructor which accepts a mac ?

**Comment by MultiMote** [comment]
https://github.com/MultiMote/niimbluelib/commit/c35cfe7370737724909cc3dcac201b5c8a31c471

You will able to do something like that in PrinterConnector.svelte

```ts
      if($printerClient instanceof NiimbotCapacitorBleClient) {
        await $printerClient.connect({deviceId: "27:03:07:17:6E:82"});
      } else {
        await $printerClient.connect();
      }
```

It will be released later.

**Comment by dotnetdreamer** [comment]
> [MultiMote/niimbluelib@c35cfe7](https://github.com/MultiMote/niimbluelib/commit/c35cfe7370737724909cc3dcac201b5c8a31c471)
> 
> You will able to do something like that in PrinterConnector.svelte
> 
> ```ts
>       if($printerClient instanceof NiimbotCapacitorBleClient) {
>         await $printerClient.connect({deviceId: "27:03:07:17:6E:82"});
>       } else {
>         await $printerClient.connect();
>       }
> ```
> 
> It will be released later.

I tried 
```
    try {
      if($printerClient instanceof NiimbotCapacitorBleClient) {
        await $printerClient.connect({deviceId: "22:05:07:4F:1B:69"});
      } else {
        await $printerClient.connect();
      }
    } catch (e) {
      if($printerClient instanceof NiimbotCapacitorBleClient) {
        await $printerClient.connect({deviceId: "69:1B:4F:07:05:22"}); // for some reasons my mac in device list shows rever. so tried this too
      }

      connectionState.set("disconnected");
      Toasts.error(e);
    }
```
But it throws:
![image](https://github.com/user-attachments/assets/f797c946-c11d-4cea-ad0d-bc8b2d7360d1)

**Comment by MultiMote** [comment]
>  for some reasons my mac in device list shows rever. so tried this too
Interesting. Bit order of B1 mac is not same as D110. Will fix it later.

What do you think about continuing the discussion on [Discord](https://discord.gg/jXPAfZVd8a)?
I don't think GitHub Issues are designed for this kind of discussion. There's also a lot here that doesn't touch on the main topic.

**Comment by dotnetdreamer** [comment]
I dont have discord, but i can join. Maybe I can contribute as well

**Comment by dotnetdreamer** [comment]
, add me there

**Comment by MultiMote** [comment]
I posted the [invite link](https://discord.gg/jXPAfZVd8a) above.
