### ISSUE TITLE
Double (cable) labels

### ISSUE THREAD

**Issue by clinkme4g** [MultiMote/niimblue#49]
Need the object's mirror function to print on double (cable) labels (12.5 x 74). 
The native app automatically copies (and mirrors) the objects from the first label's part (37 mm) to another part (next 37 mm).

**Comment by MultiMote** [comment]
Hi! Can you post a screenshot of native app with cable label? The print result will also be nice to see.

**Comment by clinkme4g** [comment]
Here is it
![Screenshot_20241117-193318-1](https://github.com/user-attachments/assets/3d869218-5886-4ba5-9892-583a84c3c79f)

**Comment by MultiMote** [comment]
Thank you. I'll try to implement this later.

**Comment by clinkme4g** [comment]
I was wrong about the app automatically copies the first part to the next. 
I need to do it by hand. The text on the both parts may be different.
So, the main enhancement should be the mirror function.
Also, would be useful to have the spacer between two parts, only for view, not for printing, 
and may be the special center function (to center the object not inside the whole label, but the specific part).

**Comment by MultiMote** [comment]
Implemented label split (label-shapes branch). Not merged yet

![image](https://github.com/user-attachments/assets/3e695a91-4c02-4d2a-b36f-6e2b6b7e3acb)

**Comment by dotnetdreamer** [comment]
> Here is it
> 
> ![Screenshot_20241117-193318-1](https://github.com/user-attachments/assets/3d869218-5886-4ba5-9892-583a84c3c79f)
> 
> 

Can you post a video of the printed label ? Kust wanna know how this look like and maybe what i am looking for...

**Comment by MultiMote** [comment]
@dotnetdreamer there are many variants of cable labels.

<details>
  <summary>Images</summary>
  
![image](https://github.com/user-attachments/assets/36963d91-20ba-4e6f-acf4-be4dea340873)

![image](https://github.com/user-attachments/assets/14e45614-f523-4b86-9885-b02bd377cb16)

![image](https://github.com/user-attachments/assets/73530a1d-eaa6-46f9-b70e-1f9203e18d0b)

</details>

Not sure I want to implement all of them.

**Comment by dotnetdreamer** [comment]
> @dotnetdreamer there are many variants of cable labels.
> 
> Images
> ![image](https://private-user-images.githubusercontent.com/8068160/389212767-36963d91-20ba-4e6f-acf4-be4dea340873.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzODcxMzYsIm5iZiI6MTczMjM4NjgzNiwicGF0aCI6Ii84MDY4MTYwLzM4OTIxMjc2Ny0zNjk2M2Q5MS0yMGJhLTRlNmYtYWNmNC1iZTRkZWEzNDA4NzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjNUMTgzMzU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2QwYTA4ZmVmMTdjNjQxZjNkOGY0N2ZkZjgxODA0YTk2ZTRmOTgwNjJiMzBiY2EyNjIxYTA0NDZiOWY5NWJjMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.AOgvmnLmCoUMCb5WRbTj8Ik9uJ0VtzhYzHV7WpSGeGc)
> 
> ![image](https://private-user-images.githubusercontent.com/8068160/389212771-14e45614-f523-4b86-9885-b02bd377cb16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzODcxMzYsIm5iZiI6MTczMjM4NjgzNiwicGF0aCI6Ii84MDY4MTYwLzM4OTIxMjc3MS0xNGU0NTYxNC1mNTIzLTRiODYtOTg4NS1iMDJiZDM3N2NiMTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjNUMTgzMzU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmIyMTlkZTBjYjQxYWMxMzZmZjE5NmI5YjE1MGU4NWJiMTIyYTdmNTRkNjBhOTI1N2FlZDVhNDMxMWM1NmJlZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.GUk1TtucyJh0z2YTbdR0HhxJFHXJ0C6vrsIeujTp_Wg)
> 
> ![image](https://private-user-images.githubusercontent.com/8068160/389212796-73530a1d-eaa6-46f9-b70e-1f9203e18d0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzODcxMzYsIm5iZiI6MTczMjM4NjgzNiwicGF0aCI6Ii84MDY4MTYwLzM4OTIxMjc5Ni03MzUzMGExZC1lYWE2LTQ2ZjktYjcwZS0xZjkyMDNlMThkMGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjNUMTgzMzU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzgzMDVlYTJkNDRiZjBmZjljNzQzZTQzY2U3YjhiZGMzZDE3NDdlZTdjZjM0YmYyNGY2OWI5YTIzYTQ0MjZlMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.u6JFIngWer2saxrIEVFfsbKi3cDfd-rTVWHCs_0ZzN4)
> 
> Not sure I want to implement all of them.

then it would be nicer to document what are supported cable type rollers as well

**Comment by MultiMote** [comment]
Double labels implemented (visual).

[vivaldi_NHYzp7b0S6.webm](https://github.com/user-attachments/assets/5f236128-fa85-4448-bd3f-d09bd0b925d9)

Mirroring has not yet implemented. It is not such a simple task.

**Comment by MultiMote** [comment]
Mirroring implemented

[vivaldi_QiN2jKpGgi.webm](https://github.com/user-attachments/assets/9eba5279-0d24-4c59-9888-4a0bf13b10cb)

**Comment by MultiMote** [comment]
> and may be the special center function (to center the object not inside the whole label, but the specific part)

Implemented too.
