### ISSUE TITLE
B1 printing issues

### ISSUE THREAD

**Issue by tywtyw2002** [MultiMote/niimblue#5]
Its seems has printing problem with B1.

In the following cases, the B1 not printing.
- Test big enough. [1]
- Multiple row text [2] [3]

In these cases, the total height of text (black) great than half of label height. This maybe cause of the problem?

<img width="434" alt="Screenshot 2024-08-16 at 17 57 14" src="https://github.com/user-attachments/assets/0b21261f-8761-4e27-bbe3-7319d4a32f41">

<img width="356" alt="Screenshot 2024-08-16 at 17 59 23" src="https://github.com/user-attachments/assets/8852f7a3-c044-4d7d-8140-25032795cc6c">

<img width="362" alt="Screenshot 2024-08-16 at 18 00 47" src="https://github.com/user-attachments/assets/c796b4ff-85e8-4f98-92ab-8de235b715f8">

**Comment by MultiMote** [comment]
Very strange. I can't repeat your issue.

![photo_2024-08-17_07-13-17](https://github.com/user-attachments/assets/d40927a8-a326-421a-b68d-d3d248f0f6d0)

What connection are you using (bluetooth/serial)? What are your printer details?

![image](https://github.com/user-attachments/assets/9921cb5c-3643-4d81-9f83-edc67c86c5a5)

I have added export button for test, can you export your canvas and attach it here? Browser (transfer) logs will be useful too (press F12, "Console" tab).

![image](https://github.com/user-attachments/assets/ad19ad92-c0d1-4cc9-9935-3ae11075ee2c)

**Comment by tywtyw2002** [comment]
BLE
```
Model metadata:
{
 "model": "B1",
 "id": [
  4096
 ],
 "dpi": 203,
 "printDirection": "top",
 "printheadPixels": 384,
 "paperTypes": [
  1,
  2,
  5
 ]
}
Printer info:
{
 "connectResult": 3,
 "protocolVersion": 3,
 "model_id": 4096,
 "serial": "",
 "mac": "",
 "charge": 3,
 "autoShutdownTime": 3,
 "labelType": 1
}
```

https://gist.github.com/tywtyw2002/9678be35300a2992fbec729002d861f8


[canvas.json](https://github.com/user-attachments/files/16643637/canvas.json)

**Comment by tywtyw2002** [comment]
If I reduce the size. Then it is work.

https://gist.github.com/tywtyw2002/c6df868ca319f1d851b91d4d3e28f351

[canvas.json](https://github.com/user-attachments/files/16643642/canvas.json)

**Comment by tywtyw2002** [comment]
The serial works fine.

Maybe the bluetooth stack issue? Too much data send in same time?

I will try to dump the system BLE data later tomorrow.

**Comment by MultiMote** [comment]
Tried to repeat failing print with your label parameters (320x240px) and with your exported canvas data - printed without problems. Maybe it happens on some Bluetooth adapters (no problems with TP-Link UB500 V1 and Xiaomi Redmi Note 11).

Anyway, I added delay between packets (as in the serial implementation). You can test it now.

Also I added "Import JSON" and changed format a little (I forgot to export label dimensions, it is incompatible with old exports now).

**Comment by tywtyw2002** [comment]
I saw you add 2s sleep in the code 

<img width="1169" alt="Screenshot 2024-08-18 at 00 09 04" src="https://github.com/user-attachments/assets/2d53a897-fbcf-4d50-8db1-a0629a100286">

I do not think that is the place to add delay. In the console, the log ts shows there are no delay between `PrintBitmapRow` cmd.

Maybe add some delay between each `PrintBitmapRow` sent. Or delay 0.1s for every 5 - 10 x `PrintBitmapRow` command sent to let bluetooth stack clear the buff.

**Comment by MultiMote** [comment]
Yup, mu bad. Fixed, hopefully.

**Comment by tywtyw2002** [comment]
Yes, it work now.

I change code to, the B1 now can print.

```
    if (force) {
      await Utils.sleep(10);
      return send();
    } else {
      await this.mutex.runExclusive(send);
    }
```
