### ISSUE TITLE
Editor / parts that can be refactored

### ISSUE THREAD

**Issue by talaviram** [MultiMote/niimblue#7]
Hi,
I’ve made a basic Apple eco-system niimbot stack (https://github.com/talaviram/libreniim)
My higher goal is to make reusable web canvas (based on vanilla html5/js fabricjs) to be used for the Apple side and the Web (Chrome/WebBLE) side.

Today I’ve pushed my current state. (https://github.com/talaviram/libreniim/tree/labeleditor/web/labeleditor)
As I’m looking for a web-based permissive (MIT) Niimbot web-stack I’ve got here and wasn’t able to find a way to contact except issue and telegram.

So far I’ve implemented some areas that might be useful also for your project. (hacky QR support, buggish object-alignment)

**Comment by MultiMote** [comment]
Hello!

I looked at [web/labeleditor](https://github.com/talaviram/libreniim/tree/labeleditor/web/labeleditor) (started dev server). The functionality so far is similar to what I did and there's no solid reason to think about integrating it into this project.

What about web stack, there is no released library yet (it will be released with MIT license), but you can try to use it now. Source code is here at the moment, but it is very unfinished: https://gitee.mmote.ru/MultiMote/niimblue-nightly

[niimblue](https://gitee.mmote.ru/MultiMote/niimblue-nightly/src/branch/master/niimblue) is frontend, [niimbluelib](https://gitee.mmote.ru/MultiMote/niimblue-nightly/src/branch/master/niimbluelib) is printer interface. There is no documentation yet. Some sort of usage example you can find in `niimblue/src/stores.ts`, `niimblue/src/lib/PrinterConnector.svelte` and `niimblue/src/lib/PrintPreview.svelte`.

Stay tuned 😁

**Comment by talaviram** [comment]
I didn’t see QR at least running from 
https://dev.mmote.ru/niimblue/
(I have QR approach which works if needed)

**Comment by MultiMote** [comment]
QR Code feature is now here (done by @xfqz86).

If needed, I'll re-open this issue later.
