### ISSUE TITLE
npm package release?

### ISSUE THREAD

**Issue by craftycram** [MultiMote/niimblue#8]
just a simple question. are you planning on releasing niimbluelib as an npm package?  
I went through your roadmap and only found `publishing code`, so not sure if a package is planned.  

i'm currently doing a project where i could use niimbluelib. should i implement the protocol myself or wait on your package?

best regards,
marc

**Comment by MultiMote** [comment]
Sure, I will publish a package.

In the meantime, you can built it, then add to your project via `yarn add file:/path/to/niimbluelib` or `npm install file:/path/to/niimbluelib`

**Comment by MultiMote** [comment]
The NPM package [has been published](https://www.npmjs.com/package/@mmote/niimbluelib).

**Comment by craftycram** [comment]
Awesome thank you!
